import type { Session, Project } from './types';

export const MOCK_SESSIONS: Session[] = [
  {
    id: 'ses-001',
    title: 'Refactor JWT middleware to support refresh tokens',
    date: '2026-03-18T14:32:00Z',
    durationMinutes: 47,
    turns: 23,
    linesOfCode: 312,
    toolCalls: 90,
    status: 'published',
    projectName: 'auth-service',
    sessionRef: 'REF_AUTH_042',
    context: 'Legacy auth used symmetric HS256 with single-token expiry. Needed asymmetric signing and refresh token rotation for microservice architecture.',
    developerTake: 'The tricky part was getting token rotation right without causing race conditions on concurrent requests. We moved from symmetric secrets to an asymmetric signing approach using Ed25519, which simplified our microservice verification logic significantly.',
    skills: ['Node.js', 'JWT Security', 'Ed25519', 'Redis', 'Microservices'],
    executionPath: [
      { stepNumber: 1, title: 'Audit existing middleware', description: 'Identified legacy HS256 dependency and single-token expiry limitations in the core auth service.', type: 'analysis' },
      { stepNumber: 2, title: 'Switched to asymmetric signing', description: 'Implemented EdDSA (Ed25519) for signing tokens, allowing public key distribution to edge nodes.', type: 'implementation' },
      { stepNumber: 3, title: 'Drafted Refresh Token Schema', description: 'Designed the Redis-backed storage for refresh token rotation and revocation lists.', type: 'implementation' },
      { stepNumber: 4, title: 'Race Condition Mitigation', description: 'Added a 30-second grace period for rotated tokens to handle frontend batch requests.', type: 'decision' },
      { stepNumber: 5, title: 'Production Rollout', description: 'Executed canary deployment with zero-downtime session migration.', type: 'deployment' },
    ],
    toolBreakdown: [
      { tool: 'Read', count: 28 },
      { tool: 'Edit', count: 22 },
      { tool: 'Write', count: 15 },
      { tool: 'Bash', count: 14 },
      { tool: 'Grep', count: 11 },
    ],
    filesChanged: [
      { path: 'src/middleware/auth.ts', additions: 241, deletions: 0 },
      { path: 'src/services/token_service.ts', additions: 88, deletions: 0 },
      { path: 'src/utils/crypto.legacy.js', additions: 0, deletions: 112 },
      { path: 'src/config/jwt.config.ts', additions: 34, deletions: 18 },
      { path: 'test/auth.test.ts', additions: 156, deletions: 42 },
    ],
    turnTimeline: [
      { timestamp: '14:02:11', type: 'prompt', content: 'The existing auth was frankencode — three different token systems' },
      { timestamp: '14:08:30', type: 'tool', content: 'Read src/middleware/auth.ts' },
      { timestamp: '14:15:44', type: 'response', content: 'Identified HS256 dependency. Proposing Ed25519 migration.' },
      { timestamp: '14:32:10', type: 'tool', content: 'Write src/services/token_service.ts' },
      { timestamp: '14:49:02', type: 'response', content: 'All 42 specs passing. Build hash 7f2d01e.' },
    ],
    rawLog: [
      '> The existing auth was frankencode',
      '> three different token systems',
      '> layered on top of each other',
      '...',
      '[AI] I can help patch the existing system',
      '> No. Tear it all out. Start fresh.',
      '...',
      '[309 tests passing]',
    ],
  },
  {
    id: 'ses-002',
    title: 'Add OAuth2 provider abstraction layer',
    date: '2026-03-17T09:15:00Z',
    durationMinutes: 63,
    turns: 31,
    linesOfCode: 487,
    toolCalls: 72,
    status: 'draft',
    projectName: 'auth-service',
    sessionRef: 'REF_AUTH_041',
    context: 'Hardcoded Google OAuth in auth.controller.ts. Need a provider interface to support GitHub, GitLab, and custom OIDC.',
    developerTake: 'The provider pattern was straightforward but the token normalization across different OAuth specs was surprisingly inconsistent. GitHub returns expires_in as seconds, Google as a timestamp.',
    skills: ['TypeScript', 'OAuth2', 'Design Patterns', 'API Integration'],
    executionPath: [
      { stepNumber: 1, title: 'Analyze hardcoded OAuth', description: 'Found Google OAuth directly in auth.controller.ts with no abstraction.', type: 'analysis' },
      { stepNumber: 2, title: 'Design provider interface', description: 'Created OAuthProvider abstract class with authenticate, refresh, and revoke methods.', type: 'implementation' },
      { stepNumber: 3, title: 'Implement Google provider', description: 'Extracted existing logic into GoogleProvider extends OAuthProvider.', type: 'implementation' },
      { stepNumber: 4, title: 'Add GitHub provider', description: 'Implemented GitHubProvider with token normalization for different expiry formats.', type: 'implementation' },
    ],
    toolBreakdown: [
      { tool: 'Read', count: 22 },
      { tool: 'Write', count: 18 },
      { tool: 'Edit', count: 14 },
      { tool: 'Bash', count: 10 },
      { tool: 'Grep', count: 8 },
    ],
    filesChanged: [
      { path: 'src/providers/OAuthProvider.ts', additions: 67, deletions: 0 },
      { path: 'src/providers/GoogleProvider.ts', additions: 94, deletions: 0 },
      { path: 'src/providers/GitHubProvider.ts', additions: 112, deletions: 0 },
      { path: 'src/auth.controller.ts', additions: 12, deletions: 156 },
    ],
    turnTimeline: [
      { timestamp: '09:15:00', type: 'prompt', content: 'Create an abstraction layer for OAuth2 providers' },
      { timestamp: '09:22:15', type: 'tool', content: 'Read src/auth.controller.ts' },
      { timestamp: '09:45:30', type: 'response', content: 'Created OAuthProvider interface with 3 methods' },
      { timestamp: '10:18:00', type: 'response', content: '22 tests passing' },
    ],
    rawLog: [
      '> create an abstraction layer for OAuth2 providers',
      '> Analyzing existing OAuth implementation...',
      '> Found hardcoded Google OAuth in auth.controller.ts',
      '> Proposing provider interface pattern',
      '[AI] Created src/providers/OAuthProvider.ts',
      '[AI] Implemented GoogleProvider extends OAuthProvider',
      '...',
      '[22 tests passing]',
    ],
  },
  {
    id: 'ses-003',
    title: 'Build ETL pipeline for event stream processing',
    date: '2026-03-16T11:00:00Z',
    durationMinutes: 89,
    turns: 42,
    linesOfCode: 634,
    toolCalls: 118,
    status: 'published',
    projectName: 'data-pipeline',
    sessionRef: 'REF_DATA_017',
    context: 'Kafka event stream had no transform layer. Raw events went straight to Postgres, causing schema drift and slow queries.',
    developerTake: 'The batch windowing was the key insight. Instead of processing events individually, we accumulate for 500ms then bulk-transform. Cut DB writes by 85% and latency by 60%.',
    skills: ['Kafka', 'ETL', 'PostgreSQL', 'Batch Processing', 'TypeScript'],
    executionPath: [
      { stepNumber: 1, title: 'Profile existing consumer', description: 'Found src/consumers/eventConsumer.ts doing individual INSERTs per event.', type: 'analysis' },
      { stepNumber: 2, title: 'Design transform layer', description: 'Created EventTransformer with configurable batch window and schema validation.', type: 'implementation' },
      { stepNumber: 3, title: 'Implement batch accumulator', description: 'Built 500ms sliding window with flush-on-full for high-throughput periods.', type: 'implementation' },
      { stepNumber: 4, title: 'Add dead letter queue', description: 'Events failing validation route to DLQ with original payload and error context.', type: 'decision' },
      { stepNumber: 5, title: 'Load test and tune', description: 'Ran 50k events/sec load test. Tuned batch size from 100 to 500 events.', type: 'testing' },
    ],
    toolBreakdown: [
      { tool: 'Read', count: 35 },
      { tool: 'Write', count: 28 },
      { tool: 'Bash', count: 22 },
      { tool: 'Edit', count: 18 },
      { tool: 'Grep', count: 15 },
    ],
    filesChanged: [
      { path: 'src/transforms/EventTransformer.ts', additions: 198, deletions: 0 },
      { path: 'src/consumers/eventConsumer.ts', additions: 45, deletions: 89 },
      { path: 'src/utils/batchAccumulator.ts', additions: 134, deletions: 0 },
      { path: 'src/queues/deadLetter.ts', additions: 67, deletions: 0 },
    ],
    turnTimeline: [
      { timestamp: '11:00:00', type: 'prompt', content: 'Set up an ETL pipeline for our Kafka event stream' },
      { timestamp: '11:12:00', type: 'tool', content: 'Read src/consumers/eventConsumer.ts' },
      { timestamp: '11:45:00', type: 'response', content: 'Created EventTransformer with batch window' },
      { timestamp: '12:29:00', type: 'response', content: 'Load test: 50k events/sec sustained' },
    ],
    rawLog: [
      '> set up an ETL pipeline for our Kafka event stream',
      '> Reading existing consumer setup...',
      '> Found src/consumers/eventConsumer.ts',
      '[AI] Proposing transform layer architecture',
      '[AI] Created src/transforms/EventTransformer.ts',
      '> Added batch processing with configurable window',
      '...',
      '[18 tests passing]',
    ],
  },
  {
    id: 'ses-004',
    title: 'Implement accessible dropdown component',
    date: '2026-03-15T16:20:00Z',
    durationMinutes: 34,
    turns: 18,
    linesOfCode: 198,
    toolCalls: 41,
    status: 'draft',
    projectName: 'ui-components',
    context: 'Design system needed an accessible dropdown with full keyboard navigation and screen reader support.',
    skills: ['React', 'Accessibility', 'ARIA', 'CSS'],
    executionPath: [
      { stepNumber: 1, title: 'Scaffold component', description: 'Created Dropdown with role="listbox" and aria-activedescendant.', type: 'implementation' },
      { stepNumber: 2, title: 'Keyboard navigation', description: 'Arrow keys, Home/End, type-ahead search, Escape to close.', type: 'implementation' },
      { stepNumber: 3, title: 'A11y audit', description: 'Ran axe-core: 0 violations, 0 incomplete checks.', type: 'testing' },
    ],
    toolBreakdown: [
      { tool: 'Write', count: 14 },
      { tool: 'Read', count: 10 },
      { tool: 'Bash', count: 9 },
      { tool: 'Edit', count: 8 },
    ],
    filesChanged: [
      { path: 'src/components/Dropdown.tsx', additions: 142, deletions: 0 },
      { path: 'src/components/Dropdown.test.tsx', additions: 56, deletions: 0 },
    ],
    turnTimeline: [
      { timestamp: '16:20:00', type: 'prompt', content: 'Build an accessible dropdown with keyboard nav' },
      { timestamp: '16:35:00', type: 'tool', content: 'Write src/components/Dropdown.tsx' },
      { timestamp: '16:54:00', type: 'response', content: '0 a11y violations' },
    ],
    rawLog: [
      '> build an accessible dropdown with keyboard nav',
      '[AI] Creating Dropdown component with ARIA attributes...',
      '[AI] Added role="listbox" and aria-activedescendant',
      '> Implemented arrow key navigation',
      '> Added Home/End key support',
      '...',
      '[0 a11y violations]',
    ],
  },
  {
    id: 'ses-005',
    title: 'Add request validation and error serialization',
    date: '2026-03-14T13:45:00Z',
    durationMinutes: 52,
    turns: 27,
    linesOfCode: 401,
    toolCalls: 65,
    status: 'archived',
    projectName: 'api-gateway',
    context: '14 route handlers had no input validation. Needed Zod schemas and consistent error responses.',
    skills: ['Zod', 'Express', 'Error Handling', 'TypeScript'],
    executionPath: [
      { stepNumber: 1, title: 'Scan route definitions', description: 'Found 14 route handlers without input validation in src/routes/.', type: 'analysis' },
      { stepNumber: 2, title: 'Create validation middleware', description: 'Built validate() middleware that accepts Zod schemas for body, params, and query.', type: 'implementation' },
      { stepNumber: 3, title: 'Standardize error format', description: 'Created ErrorSerializer with consistent { code, message, details } shape.', type: 'implementation' },
      { stepNumber: 4, title: 'Retrofit all routes', description: 'Added Zod schemas to all 14 handlers. Coverage: 94%.', type: 'implementation' },
    ],
    toolBreakdown: [
      { tool: 'Read', count: 20 },
      { tool: 'Edit', count: 18 },
      { tool: 'Bash', count: 12 },
      { tool: 'Write', count: 10 },
      { tool: 'Grep', count: 5 },
    ],
    filesChanged: [
      { path: 'src/middleware/validate.ts', additions: 89, deletions: 0 },
      { path: 'src/utils/ErrorSerializer.ts', additions: 45, deletions: 0 },
      { path: 'src/routes/users.ts', additions: 28, deletions: 4 },
    ],
    turnTimeline: [
      { timestamp: '13:45:00', type: 'prompt', content: 'Add zod validation to all API routes' },
      { timestamp: '13:52:00', type: 'tool', content: 'Grep route handlers without validation' },
      { timestamp: '14:37:00', type: 'response', content: '31 tests passing, coverage: 94%' },
    ],
    rawLog: [
      '> add zod validation to all API routes',
      '> Scanning route definitions in src/routes/...',
      '> Found 14 route handlers without input validation',
      '[AI] Proposing validation middleware pattern',
      '[AI] Created src/middleware/validate.ts',
      '...',
      '[31 tests passing, coverage: 94%]',
    ],
  },
  {
    id: 'ses-006',
    title: 'Optimize batch insert performance for high-volume ingestion',
    date: '2026-03-13T10:10:00Z',
    durationMinutes: 71,
    turns: 35,
    linesOfCode: 289,
    toolCalls: 84,
    status: 'published',
    projectName: 'data-pipeline',
    sessionRef: 'REF_DATA_016',
    context: 'Event ingestion dropping events at peak load. Individual INSERTs bottlenecking at 12k events/sec.',
    developerTake: 'The COPY protocol was the game changer. We were doing individual INSERTs in a loop like amateurs. Switching to pg COPY with UNNEST got us to 48k events/sec with lower CPU.',
    skills: ['PostgreSQL', 'Performance', 'COPY Protocol', 'Node.js'],
    executionPath: [
      { stepNumber: 1, title: 'Profile insert path', description: 'Found individual INSERTs in a loop. Bottleneck at 12k events/sec.', type: 'analysis' },
      { stepNumber: 2, title: 'Implement bulk INSERT', description: 'Replaced loop with multi-row INSERT using UNNEST for array binding.', type: 'implementation' },
      { stepNumber: 3, title: 'Switch to COPY protocol', description: 'Rewrote sink to use pg COPY for maximum throughput.', type: 'implementation' },
      { stepNumber: 4, title: 'Benchmark results', description: 'Throughput: 12k to 48k events/sec. CPU usage down 40%.', type: 'testing' },
    ],
    toolBreakdown: [
      { tool: 'Read', count: 25 },
      { tool: 'Edit', count: 20 },
      { tool: 'Bash', count: 18 },
      { tool: 'Write', count: 12 },
      { tool: 'Grep', count: 9 },
    ],
    filesChanged: [
      { path: 'src/sink/pgSink.ts', additions: 145, deletions: 67 },
      { path: 'src/sink/copyStream.ts', additions: 89, deletions: 0 },
      { path: 'bench/insert_benchmark.ts', additions: 55, deletions: 0 },
    ],
    turnTimeline: [
      { timestamp: '10:10:00', type: 'prompt', content: 'Optimize the batch insert — dropping events at peak' },
      { timestamp: '10:18:00', type: 'tool', content: 'Read src/sink/pgSink.ts' },
      { timestamp: '10:45:00', type: 'response', content: 'Implemented COPY protocol sink' },
      { timestamp: '11:21:00', type: 'response', content: 'Throughput: 12k to 48k events/sec' },
    ],
    rawLog: [
      '> optimize the batch insert — dropping events at peak',
      '> Profiling current insert path...',
      '> Bottleneck: individual INSERTs in a loop',
      '[AI] Proposing bulk INSERT with UNNEST',
      '[AI] Rewrote sink to use pg COPY protocol',
      '...',
      '[Throughput: 12k → 48k events/sec]',
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  { name: 'auth-service', sessionCount: 2, description: 'JWT auth and OAuth provider layer' },
  { name: 'data-pipeline', sessionCount: 2, description: 'Event stream ETL and ingestion' },
  { name: 'ui-components', sessionCount: 1, description: 'Accessible component library' },
  { name: 'api-gateway', sessionCount: 1, description: 'Request validation and routing' },
];
