defmodule HeyiAmAppWeb.Router do
  use HeyiAmAppWeb, :router

  import HeyiAmAppWeb.UserAuth

  # -- Pipelines -------------------------------------------------------

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {HeyiAmAppWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers, %{
      "content-security-policy" =>
        "default-src 'self'; " <>
        "script-src 'self' https://analytics.interactivecats.com https://static.cloudflareinsights.com; " <>
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; " <>
        "font-src https://fonts.gstatic.com; " <>
        "img-src 'self' data: https:; " <>
        "connect-src 'self' https://analytics.interactivecats.com https://cloudflareinsights.com; " <>
        "frame-ancestors 'self'"
    }
    plug :fetch_current_scope_for_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug HeyiAmAppWeb.Plugs.ApiAuth
  end

  pipeline :require_api_auth do
    plug HeyiAmAppWeb.Plugs.RequireApiAuth
  end

  pipeline :rate_limit_auth do
    plug HeyiAmAppWeb.Plugs.RateLimit, action: "auth", limit: 5, period: 60_000
  end

  pipeline :rate_limit_api_session do
    plug HeyiAmAppWeb.Plugs.RateLimit, action: "api_session", limit: 30, period: 60_000
  end

  pipeline :rate_limit_device_poll do
    plug HeyiAmAppWeb.Plugs.RateLimit, action: "device_poll", limit: 20, period: 60_000
  end

  pipeline :rate_limit_enhance do
    plug HeyiAmAppWeb.Plugs.RateLimit, action: "enhance", limit: 5, period: 60_000
  end

  # -- API routes -------------------------------------------------------

  scope "/api", HeyiAmAppWeb do
    pipe_through [:api, :rate_limit_auth]

    post "/device/code", DeviceApiController, :create_code
  end

  scope "/api", HeyiAmAppWeb do
    pipe_through [:api, :rate_limit_device_poll]

    post "/device/token", DeviceApiController, :poll_token
  end

  scope "/api", HeyiAmAppWeb do
    pipe_through [:api, :rate_limit_auth]

    get "/auth/status", DeviceApiController, :auth_status
    get "/username/check", UsernameApiController, :check
  end

  scope "/api", HeyiAmAppWeb do
    pipe_through [:api, :api_auth, :require_api_auth, :rate_limit_enhance]

    post "/enhance", EnhanceApiController, :create
  end

  scope "/api", HeyiAmAppWeb do
    pipe_through [:api, :api_auth, :require_api_auth, :rate_limit_api_session]

    post "/projects", ProjectApiController, :create
    post "/projects/:slug/screenshot-url", ProjectApiController, :screenshot_url
    patch "/projects/:slug/screenshot-key", ProjectApiController, :update_screenshot_key
    post "/sessions", ShareApiController, :create
    post "/time-stats", TimeStatsApiController, :upload
    patch "/profile", ProfileApiController, :update
  end

  scope "/api", HeyiAmAppWeb do
    pipe_through [:api]

    get "/projects/:username/:slug/screenshot", ProjectApiController, :screenshot
  end

  # -- Admin dashboard ---------------------------------------------------

  import Phoenix.LiveDashboard.Router

  scope "/admin" do
    pipe_through [:browser]

    live_dashboard "/dashboard",
      metrics: HeyiAmAppWeb.Telemetry,
      on_mount: [{HeyiAmAppWeb.AdminAuth, :admin}]
  end

  # Dev mailbox
  if Application.compile_env(:heyi_am_app_web, :dev_routes) do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  # -- OAuth routes ------------------------------------------------------

  scope "/auth", HeyiAmAppWeb do
    pipe_through [:browser]

    get "/:provider", OAuthController, :request
    get "/:provider/callback", OAuthController, :callback
  end

  # -- Public pages (landing, legal) — no auth required ------------------

  scope "/", HeyiAmAppWeb do
    pipe_through [:browser]

    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
  end

  # -- Root route --------------------------------------------------------

  scope "/", HeyiAmAppWeb do
    pipe_through [:browser]

    get "/", PageController, :home
  end

  # -- Auth routes (generated by phx.gen.auth) ---------------------------

  scope "/", HeyiAmAppWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :require_authenticated_user,
      on_mount: [{HeyiAmAppWeb.UserAuth, :require_authenticated}] do
      live "/dashboard", DashboardLive
      live "/users/settings", UserLive.Settings, :edit
      live "/users/settings/confirm-email/:token", UserLive.Settings, :confirm_email
      live "/onboarding/username", ClaimUsernameLive
      live "/device", DeviceAuthLive
    end

    post "/users/update-password", UserSessionController, :update_password
    get "/users/settings/export", UserSessionController, :export
    delete "/users/settings/delete-account", UserSessionController, :delete_account

    get "/preview/project/:slug", PreviewController, :project
    get "/preview/session/:id", PreviewController, :session
  end

  scope "/", HeyiAmAppWeb do
    pipe_through [:browser]

    live_session :current_user,
      on_mount: [{HeyiAmAppWeb.UserAuth, :mount_current_scope}] do
      live "/users/register", UserLive.Registration, :new
      live "/users/log-in", UserLive.Login, :new
      live "/users/log-in/:token", UserLive.Confirmation, :new
      live "/users/reset-password", UserLive.ForgotPassword, :new
      live "/users/reset-password/:token", UserLive.ResetPassword, :edit
    end

    delete "/users/log-out", UserSessionController, :delete
  end

  scope "/", HeyiAmAppWeb do
    pipe_through [:browser, :rate_limit_auth]

    post "/users/log-in", UserSessionController, :create
    post "/users/register", UserSessionController, :register_and_login
  end
end
