// Demo data for marketing videos and screenshots.
// All data is fictional — no real names, paths, or PII.

import type { Session } from './analyzer.js';
import type { SearchResult } from './search.js';
import type { SourceAuditResult } from './source-audit.js';
import type { TranscriptResponse } from './transcript.js';

// ── Helpers ──────────────────────────────────────────────────

function isoDate(month: number, day: number, hour = 10, min = 0): string {
  return `2026-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}T${String(hour).padStart(2, '0')}:${String(min).padStart(2, '0')}:00.000Z`;
}

// ── Project metadata ─────────────────────────────────────────

export const DEMO_PROJECTS = {
  budgetwise: {
    dirName: '-Users-alex-Dev-budgetwise',
    name: 'budgetwise',
    cwd: '/Users/alex/Dev/budgetwise',
    skills: ['TypeScript', 'React', 'Next.js', 'Prisma', 'PostgreSQL', 'Tailwind CSS', 'Stripe API'],
  },
  shellhook: {
    dirName: '-Users-alex-Dev-shellhook',
    name: 'shellhook',
    cwd: '/Users/alex/Dev/shellhook',
    skills: ['Rust', 'CLI design', 'TOML parsing', 'Git internals', 'Shell scripting'],
  },
  pixelboard: {
    dirName: '-Users-alex-Dev-pixelboard',
    name: 'pixelboard',
    cwd: '/Users/alex/Dev/pixelboard',
    skills: ['TypeScript', 'WebSocket', 'Canvas API', 'Redis', 'Express'],
  },
} as const;

// ── Budgetwise sessions (28) ─────────────────────────────────

const budgetwiseSessions: Session[] = [
  {
    id: 'demo-a1b2-c3d4',
    title: 'Set up Prisma schema with User, Account, and Transaction models',
    date: isoDate(2, 3, 9, 15),
    endTime: isoDate(2, 3, 10, 42),
    durationMinutes: 72,
    wallClockMinutes: 87,
    turns: 45,
    linesOfCode: 680,
    status: 'enhanced',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Set up Prisma schema', 'Created User model', 'Added Account model with balance tracking', 'Transaction model with polymorphic types'],
    skills: ['TypeScript', 'Prisma', 'PostgreSQL'],
    executionPath: [
      { stepNumber: 1, title: 'Schema design', description: 'Sketched out the core models — User, Account, Transaction. Decided on a discriminated union for transaction types instead of STI.' },
      { stepNumber: 2, title: 'Prisma setup', description: 'Initialized Prisma with PostgreSQL, wrote the schema file with proper relations and indexes.' },
      { stepNumber: 3, title: 'Migration', description: 'Ran the initial migration, fixed a cascade delete issue on Account -> Transaction.' },
      { stepNumber: 4, title: 'Seed data', description: 'Created a seed script with realistic test data — multiple accounts, mixed transaction types.' },
    ],
    toolBreakdown: [
      { tool: 'Edit', count: 18 },
      { tool: 'Read', count: 12 },
      { tool: 'Bash', count: 9 },
      { tool: 'Write', count: 4 },
      { tool: 'Grep', count: 2 },
    ],
    filesChanged: [
      { path: 'prisma/schema.prisma', additions: 142, deletions: 0 },
      { path: 'prisma/seed.ts', additions: 89, deletions: 0 },
      { path: 'src/lib/db.ts', additions: 34, deletions: 0 },
      { path: 'prisma/migrations/20260203_init/migration.sql', additions: 415, deletions: 0 },
    ],
    turnTimeline: [
      { timestamp: isoDate(2, 3, 9, 15), type: 'prompt', content: 'Set up a Prisma schema for a personal finance app. I need User, Account, and Transaction models.' },
      { timestamp: isoDate(2, 3, 9, 18), type: 'response', content: 'Created the initial schema with three models and their relations.' },
      { timestamp: isoDate(2, 3, 9, 25), type: 'tool', content: 'Edit prisma/schema.prisma' },
      { timestamp: isoDate(2, 3, 9, 40), type: 'prompt', content: 'Transactions need to support different types — income, expense, transfer. Use a discriminated union, not single-table inheritance.' },
    ],
    toolCalls: 45,
    qaPairs: [
      { question: 'Why did you choose a discriminated union over single-table inheritance for transaction types?', answer: 'STI would have left nullable columns everywhere — transferTo only makes sense for transfers, recurringSchedule only for recurring. The union pattern keeps each type clean and the TypeScript compiler catches missing fields.' },
      { question: 'How does the cascade delete work between Account and Transaction?', answer: 'Deleting an account cascades to its transactions. Initially had it set to restrict, but that made account cleanup impossible without manual transaction deletion first.' },
    ],
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-schema', role: 'backend-dev', durationMinutes: 35, linesOfCode: 280, date: isoDate(2, 3, 9, 18) },
      { sessionId: 'demo-sub2-schema', role: 'backend-dev', durationMinutes: 25, linesOfCode: 142, date: isoDate(2, 3, 9, 18) },
      { sessionId: 'demo-sub3-schema', role: 'qa-engineer', durationMinutes: 20, linesOfCode: 89, date: isoDate(2, 3, 9, 19) },
      { sessionId: 'demo-sub4-schema', role: 'security-engineer', durationMinutes: 15, linesOfCode: 45, date: isoDate(2, 3, 9, 19) },
      { sessionId: 'demo-sub5-schema', role: 'code-reviewer', durationMinutes: 22, linesOfCode: 30, date: isoDate(2, 3, 10, 0) },
      { sessionId: 'demo-sub6-schema', role: 'frontend-dev', durationMinutes: 18, linesOfCode: 120, date: isoDate(2, 3, 10, 0) },
      { sessionId: 'demo-sub7-schema', role: 'qa-engineer', durationMinutes: 12, linesOfCode: 60, date: isoDate(2, 3, 10, 1) },
    ],
  },
  {
    id: 'demo-e5f6-g7h8',
    title: 'Build transaction list page with infinite scroll',
    date: isoDate(2, 5, 14, 0),
    endTime: isoDate(2, 5, 15, 22),
    durationMinutes: 65,
    wallClockMinutes: 82,
    turns: 38,
    linesOfCode: 520,
    status: 'enhanced',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Transaction list page', 'Infinite scroll with cursor pagination', 'Filter by account and date range'],
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
    executionPath: [
      { stepNumber: 1, title: 'API route', description: 'Built the /api/transactions endpoint with cursor-based pagination. Returns 50 items per page with a nextCursor field.' },
      { stepNumber: 2, title: 'List component', description: 'React component with IntersectionObserver for infinite scroll. Debounced the observer to avoid rapid re-fetches.' },
      { stepNumber: 3, title: 'Filters', description: 'Added account selector and date range picker. Filters reset the cursor and refetch.' },
    ],
    toolBreakdown: [
      { tool: 'Edit', count: 15 },
      { tool: 'Read', count: 10 },
      { tool: 'Bash', count: 8 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/app/api/transactions/route.ts', additions: 78, deletions: 0 },
      { path: 'src/components/TransactionList.tsx', additions: 195, deletions: 0 },
      { path: 'src/components/TransactionFilters.tsx', additions: 112, deletions: 0 },
      { path: 'src/hooks/useInfiniteTransactions.ts', additions: 65, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 36,
    qaPairs: [
      { question: 'Why cursor-based pagination instead of offset?', answer: 'Offset pagination breaks when transactions are added or deleted between pages — you either skip items or show duplicates. Cursor pagination is stable because it anchors to a specific row.' },
    ],
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-txlist', role: 'frontend-dev', durationMinutes: 30, linesOfCode: 295, date: isoDate(2, 5, 14, 5) },
      { sessionId: 'demo-sub2-txlist', role: 'backend-dev', durationMinutes: 20, linesOfCode: 178, date: isoDate(2, 5, 14, 5) },
      { sessionId: 'demo-sub3-txlist', role: 'qa-engineer', durationMinutes: 15, linesOfCode: 65, date: isoDate(2, 5, 14, 6) },
      { sessionId: 'demo-sub4-txlist', role: 'ux-designer', durationMinutes: 18, linesOfCode: 40, date: isoDate(2, 5, 14, 6) },
      { sessionId: 'demo-sub5-txlist', role: 'code-reviewer', durationMinutes: 12, linesOfCode: 20, date: isoDate(2, 5, 14, 40) },
    ],
  },
  {
    id: 'demo-i9j0-k1l2',
    title: 'Implement recurring transaction detection algorithm',
    date: isoDate(2, 7, 10, 30),
    durationMinutes: 88,
    wallClockMinutes: 105,
    turns: 62,
    linesOfCode: 890,
    status: 'enhanced',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Recurring transaction detection', 'Pattern matching on amount + merchant', 'Frequency analysis'],
    skills: ['TypeScript', 'PostgreSQL', 'Algorithm design'],
    executionPath: [
      { stepNumber: 1, title: 'Analysis', description: 'Grouped transactions by normalized merchant name + amount. Looked for regular intervals (weekly, biweekly, monthly).' },
      { stepNumber: 2, title: 'Detection logic', description: 'Wrote the interval detection — tolerance window of +/- 3 days for monthly, +/- 1 day for weekly. Three consecutive matches = recurring.' },
      { stepNumber: 3, title: 'Database query', description: 'Optimized the grouping query with a partial index on merchant_normalized. Brought detection from 2s to 120ms on 10k transactions.' },
      { stepNumber: 4, title: 'Tests', description: 'Edge cases: transactions that change amount slightly over time, merchants with similar names, gaps in recurring series.' },
    ],
    toolBreakdown: [
      { tool: 'Edit', count: 22 },
      { tool: 'Read', count: 14 },
      { tool: 'Bash', count: 16 },
      { tool: 'Grep', count: 5 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/lib/recurring-detection.ts', additions: 245, deletions: 0 },
      { path: 'src/lib/recurring-detection.test.ts', additions: 310, deletions: 0 },
      { path: 'prisma/schema.prisma', additions: 12, deletions: 3 },
      { path: 'src/app/api/recurring/route.ts', additions: 45, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 60,
    qaPairs: [
      { question: 'How do you handle transactions where the amount changes slightly (e.g., variable utility bills)?', answer: 'Added a tolerance parameter — if amounts are within 15% of the median for that merchant, they still count as recurring. The user can adjust the threshold.' },
    ],
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-recur', role: 'backend-dev', durationMinutes: 45, linesOfCode: 445, date: isoDate(2, 7, 10, 35) },
      { sessionId: 'demo-sub2-recur', role: 'backend-dev', durationMinutes: 30, linesOfCode: 245, date: isoDate(2, 7, 10, 35) },
      { sessionId: 'demo-sub3-recur', role: 'qa-engineer', durationMinutes: 25, linesOfCode: 310, date: isoDate(2, 7, 10, 36) },
      { sessionId: 'demo-sub4-recur', role: 'security-engineer', durationMinutes: 20, linesOfCode: 45, date: isoDate(2, 7, 10, 36) },
      { sessionId: 'demo-sub5-recur', role: 'code-reviewer', durationMinutes: 15, linesOfCode: 20, date: isoDate(2, 7, 11, 10) },
      { sessionId: 'demo-sub6-recur', role: 'backend-dev', durationMinutes: 15, linesOfCode: 90, date: isoDate(2, 7, 11, 10) },
    ],
  },
  {
    id: 'demo-m3n4-o5p6',
    title: 'Add Stripe integration for premium features',
    date: isoDate(2, 10, 9, 0),
    durationMinutes: 55,
    wallClockMinutes: 70,
    turns: 35,
    linesOfCode: 420,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Stripe checkout session', 'Webhook handler for payment events', 'Premium feature gating'],
    skills: ['TypeScript', 'Stripe API', 'Next.js'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 14 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 6 },
      { tool: 'Write', count: 4 },
    ],
    filesChanged: [
      { path: 'src/app/api/stripe/checkout/route.ts', additions: 67, deletions: 0 },
      { path: 'src/app/api/stripe/webhook/route.ts', additions: 98, deletions: 0 },
      { path: 'src/lib/stripe.ts', additions: 45, deletions: 0 },
      { path: 'src/middleware.ts', additions: 23, deletions: 5 },
    ],
    turnTimeline: [],
    toolCalls: 32,
  },
  {
    id: 'demo-q7r8-s9t0',
    title: 'Design dashboard layout with spending charts',
    date: isoDate(2, 12, 11, 0),
    durationMinutes: 45,
    wallClockMinutes: 52,
    turns: 28,
    linesOfCode: 380,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Dashboard layout', 'Monthly spending chart', 'Category breakdown pie chart'],
    skills: ['React', 'Tailwind CSS', 'Chart.js'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 12 },
      { tool: 'Read', count: 6 },
      { tool: 'Write', count: 5 },
    ],
    filesChanged: [
      { path: 'src/app/dashboard/page.tsx', additions: 145, deletions: 0 },
      { path: 'src/components/SpendingChart.tsx', additions: 120, deletions: 0 },
      { path: 'src/components/CategoryBreakdown.tsx', additions: 95, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 23,
  },
  {
    id: 'demo-u1v2-w3x4',
    title: 'Fix currency formatting edge cases in locale-aware display',
    date: isoDate(2, 13, 15, 30),
    durationMinutes: 18,
    wallClockMinutes: 22,
    turns: 12,
    linesOfCode: 85,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'cursor',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Fix Intl.NumberFormat for JPY', 'Handle zero-decimal currencies'],
    skills: ['TypeScript'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 5 },
      { tool: 'Read', count: 4 },
      { tool: 'Bash', count: 3 },
    ],
    filesChanged: [
      { path: 'src/lib/currency.ts', additions: 32, deletions: 8 },
      { path: 'src/lib/currency.test.ts', additions: 45, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 12,
  },
  {
    id: 'demo-y5z6-a7b8',
    title: 'Add account balance reconciliation checks',
    date: isoDate(2, 14, 10, 0),
    durationMinutes: 42,
    wallClockMinutes: 55,
    turns: 30,
    linesOfCode: 310,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Balance reconciliation', 'Detect drift between computed and stored balance'],
    skills: ['TypeScript', 'PostgreSQL', 'Prisma'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 10 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 7 },
    ],
    filesChanged: [
      { path: 'src/lib/reconciliation.ts', additions: 120, deletions: 0 },
      { path: 'src/lib/reconciliation.test.ts', additions: 165, deletions: 0 },
      { path: 'src/app/api/accounts/reconcile/route.ts', additions: 25, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 25,
  },
  {
    id: 'demo-c9d0-e1f2',
    title: 'Build CSV import for bank statements',
    date: isoDate(2, 17, 9, 45),
    durationMinutes: 78,
    wallClockMinutes: 95,
    turns: 52,
    linesOfCode: 640,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['CSV parser', 'Column mapping UI', 'Duplicate detection on import'],
    skills: ['TypeScript', 'React', 'Next.js'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 20 },
      { tool: 'Read', count: 12 },
      { tool: 'Bash', count: 10 },
      { tool: 'Write', count: 5 },
    ],
    filesChanged: [
      { path: 'src/lib/csv-parser.ts', additions: 180, deletions: 0 },
      { path: 'src/components/ImportWizard.tsx', additions: 245, deletions: 0 },
      { path: 'src/app/api/import/route.ts', additions: 95, deletions: 0 },
      { path: 'src/lib/csv-parser.test.ts', additions: 120, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 47,
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-csv', role: 'backend-dev', durationMinutes: 40, linesOfCode: 280, date: isoDate(2, 17, 9, 50) },
      { sessionId: 'demo-sub2-csv', role: 'frontend-dev', durationMinutes: 35, linesOfCode: 245, date: isoDate(2, 17, 9, 50) },
      { sessionId: 'demo-sub3-csv', role: 'qa-engineer', durationMinutes: 25, linesOfCode: 120, date: isoDate(2, 17, 9, 51) },
      { sessionId: 'demo-sub4-csv', role: 'code-reviewer', durationMinutes: 15, linesOfCode: 30, date: isoDate(2, 17, 10, 25) },
      { sessionId: 'demo-sub5-csv', role: 'backend-dev', durationMinutes: 15, linesOfCode: 95, date: isoDate(2, 17, 10, 25) },
    ],
  },
  {
    id: 'demo-g3h4-i5j6',
    title: 'Implement budget categories with monthly limits',
    date: isoDate(2, 19, 13, 0),
    durationMinutes: 58,
    wallClockMinutes: 68,
    turns: 40,
    linesOfCode: 480,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Budget categories', 'Monthly spending limits', 'Overspend alerts'],
    skills: ['TypeScript', 'Prisma', 'React'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 16 },
      { tool: 'Read', count: 10 },
      { tool: 'Bash', count: 8 },
    ],
    filesChanged: [
      { path: 'prisma/schema.prisma', additions: 28, deletions: 2 },
      { path: 'src/app/api/budgets/route.ts', additions: 85, deletions: 0 },
      { path: 'src/components/BudgetManager.tsx', additions: 210, deletions: 0 },
      { path: 'src/lib/budget-alerts.ts', additions: 75, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 34,
  },
  {
    id: 'demo-k7l8-m9n0',
    title: 'Add email notifications for budget overspend',
    date: isoDate(2, 20, 16, 0),
    durationMinutes: 32,
    wallClockMinutes: 38,
    turns: 20,
    linesOfCode: 210,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Email notifications', 'Resend integration', 'Template for budget alerts'],
    skills: ['TypeScript', 'Next.js'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 8 },
      { tool: 'Read', count: 5 },
      { tool: 'Bash', count: 4 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/lib/email.ts', additions: 65, deletions: 0 },
      { path: 'src/emails/budget-alert.tsx', additions: 85, deletions: 0 },
      { path: 'src/app/api/notifications/route.ts', additions: 45, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 20,
  },
  {
    id: 'demo-o1p2-q3r4',
    title: 'Write E2E tests for transaction CRUD flow',
    date: isoDate(2, 21, 10, 0),
    durationMinutes: 48,
    wallClockMinutes: 55,
    turns: 33,
    linesOfCode: 410,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Playwright E2E tests', 'Transaction create/read/update/delete', 'Test fixtures'],
    skills: ['TypeScript', 'Playwright', 'Testing'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 14 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 12 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'tests/transactions.spec.ts', additions: 280, deletions: 0 },
      { path: 'tests/fixtures/test-data.ts', additions: 85, deletions: 0 },
      { path: 'playwright.config.ts', additions: 35, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 37,
  },
  {
    id: 'demo-s5t6-u7v8',
    title: 'Optimize transaction queries with composite indexes',
    date: isoDate(2, 24, 14, 30),
    durationMinutes: 25,
    wallClockMinutes: 30,
    turns: 15,
    linesOfCode: 120,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['EXPLAIN ANALYZE on slow queries', 'Added composite index on (account_id, created_at)', 'Removed unused index'],
    skills: ['PostgreSQL', 'Prisma'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Read', count: 6 },
      { tool: 'Bash', count: 8 },
      { tool: 'Edit', count: 4 },
    ],
    filesChanged: [
      { path: 'prisma/schema.prisma', additions: 8, deletions: 3 },
      { path: 'prisma/migrations/20260224_indexes/migration.sql', additions: 12, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 18,
  },
  {
    id: 'demo-w9x0-y1z2',
    title: 'Add dark mode with system preference detection',
    date: isoDate(2, 25, 11, 0),
    durationMinutes: 35,
    wallClockMinutes: 42,
    turns: 22,
    linesOfCode: 280,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'cursor',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Dark mode toggle', 'CSS variables', 'System preference media query'],
    skills: ['React', 'Tailwind CSS', 'CSS'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 12 },
      { tool: 'Read', count: 6 },
    ],
    filesChanged: [
      { path: 'src/app/globals.css', additions: 95, deletions: 12 },
      { path: 'src/components/ThemeToggle.tsx', additions: 48, deletions: 0 },
      { path: 'src/hooks/useTheme.ts', additions: 35, deletions: 0 },
      { path: 'tailwind.config.ts', additions: 8, deletions: 2 },
    ],
    turnTimeline: [],
    toolCalls: 18,
  },
  {
    id: 'demo-a3b4-c5d6',
    title: 'Build account settings page with profile editing',
    date: isoDate(2, 26, 9, 30),
    durationMinutes: 40,
    wallClockMinutes: 48,
    turns: 25,
    linesOfCode: 350,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Settings page', 'Profile form with validation', 'Currency preference'],
    skills: ['React', 'Next.js', 'TypeScript'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 11 },
      { tool: 'Read', count: 7 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/app/settings/page.tsx', additions: 165, deletions: 0 },
      { path: 'src/components/ProfileForm.tsx', additions: 120, deletions: 0 },
      { path: 'src/app/api/settings/route.ts', additions: 55, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 21,
  },
  {
    id: 'demo-e7f8-g9h0',
    title: 'Implement transaction search with full-text index',
    date: isoDate(3, 1, 10, 0),
    durationMinutes: 52,
    wallClockMinutes: 65,
    turns: 36,
    linesOfCode: 390,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Full-text search on transaction descriptions', 'PostgreSQL tsvector', 'Search results UI'],
    skills: ['PostgreSQL', 'TypeScript', 'React'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 13 },
      { tool: 'Read', count: 9 },
      { tool: 'Bash', count: 8 },
    ],
    filesChanged: [
      { path: 'prisma/schema.prisma', additions: 6, deletions: 0 },
      { path: 'src/app/api/transactions/search/route.ts', additions: 85, deletions: 0 },
      { path: 'src/components/TransactionSearch.tsx', additions: 145, deletions: 0 },
      { path: 'prisma/migrations/20260301_fts/migration.sql', additions: 22, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 30,
  },
  {
    id: 'demo-i1j2-k3l4',
    title: 'Add plaid integration for bank account linking',
    date: isoDate(3, 3, 13, 15),
    durationMinutes: 90,
    wallClockMinutes: 115,
    turns: 68,
    linesOfCode: 780,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Plaid Link integration', 'Token exchange flow', 'Transaction sync webhook', 'Error handling for expired tokens'],
    skills: ['TypeScript', 'Next.js', 'Plaid API'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 24 },
      { tool: 'Read', count: 15 },
      { tool: 'Bash', count: 12 },
      { tool: 'Write', count: 6 },
    ],
    filesChanged: [
      { path: 'src/lib/plaid.ts', additions: 145, deletions: 0 },
      { path: 'src/app/api/plaid/link/route.ts', additions: 65, deletions: 0 },
      { path: 'src/app/api/plaid/webhook/route.ts', additions: 120, deletions: 0 },
      { path: 'src/components/PlaidLink.tsx', additions: 85, deletions: 0 },
      { path: 'src/lib/plaid.test.ts', additions: 180, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 57,
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-plaid', role: 'backend-dev', durationMinutes: 45, linesOfCode: 330, date: isoDate(3, 3, 13, 20) },
      { sessionId: 'demo-sub2-plaid', role: 'frontend-dev', durationMinutes: 25, linesOfCode: 170, date: isoDate(3, 3, 13, 20) },
      { sessionId: 'demo-sub3-plaid', role: 'security-engineer', durationMinutes: 30, linesOfCode: 210, date: isoDate(3, 3, 13, 21) },
      { sessionId: 'demo-sub4-plaid', role: 'qa-engineer', durationMinutes: 35, linesOfCode: 180, date: isoDate(3, 3, 13, 21) },
      { sessionId: 'demo-sub5-plaid', role: 'code-reviewer', durationMinutes: 12, linesOfCode: 45, date: isoDate(3, 3, 14, 0) },
      { sessionId: 'demo-sub6-plaid', role: 'security-red-teamer', durationMinutes: 10, linesOfCode: 30, date: isoDate(3, 3, 14, 0) },
      { sessionId: 'demo-sub7-plaid', role: 'backend-dev', durationMinutes: 20, linesOfCode: 140, date: isoDate(3, 3, 14, 1) },
      { sessionId: 'demo-sub8-plaid', role: 'qa-engineer', durationMinutes: 18, linesOfCode: 90, date: isoDate(3, 3, 14, 1) },
    ],
  },
  {
    id: 'demo-m5n6-o7p8',
    title: 'Fix timezone bug in monthly spending aggregation',
    date: isoDate(3, 4, 16, 45),
    durationMinutes: 15,
    wallClockMinutes: 18,
    turns: 8,
    linesOfCode: 45,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Fix: spending totals were wrong near month boundaries', 'Use UTC consistently'],
    skills: ['TypeScript', 'PostgreSQL'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 3 },
      { tool: 'Read', count: 4 },
      { tool: 'Bash', count: 2 },
    ],
    filesChanged: [
      { path: 'src/lib/aggregation.ts', additions: 12, deletions: 8 },
      { path: 'src/lib/aggregation.test.ts', additions: 25, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 9,
  },
  {
    id: 'demo-q9r0-s1t2',
    title: 'Add transaction tagging and custom categories',
    date: isoDate(3, 6, 10, 30),
    durationMinutes: 62,
    wallClockMinutes: 75,
    turns: 42,
    linesOfCode: 520,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Transaction tags', 'Custom categories', 'Auto-categorization rules'],
    skills: ['TypeScript', 'Prisma', 'React'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 18 },
      { tool: 'Read', count: 11 },
      { tool: 'Bash', count: 7 },
    ],
    filesChanged: [
      { path: 'prisma/schema.prisma', additions: 22, deletions: 0 },
      { path: 'src/components/TagEditor.tsx', additions: 145, deletions: 0 },
      { path: 'src/lib/auto-categorize.ts', additions: 95, deletions: 0 },
      { path: 'src/app/api/categories/route.ts', additions: 68, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 36,
  },
  {
    id: 'demo-u3v4-w5x6',
    title: 'Build spending insights with trend analysis',
    date: isoDate(3, 8, 9, 0),
    durationMinutes: 70,
    wallClockMinutes: 85,
    turns: 48,
    linesOfCode: 620,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Spending trends', 'Month-over-month comparison', 'Anomaly detection for unusual spending'],
    skills: ['TypeScript', 'React', 'Chart.js'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 20 },
      { tool: 'Read', count: 12 },
      { tool: 'Bash', count: 9 },
    ],
    filesChanged: [
      { path: 'src/components/SpendingInsights.tsx', additions: 210, deletions: 0 },
      { path: 'src/lib/trend-analysis.ts', additions: 185, deletions: 0 },
      { path: 'src/lib/anomaly-detection.ts', additions: 110, deletions: 0 },
      { path: 'src/lib/trend-analysis.test.ts', additions: 115, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 41,
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-insights', role: 'backend-dev', durationMinutes: 35, linesOfCode: 285, date: isoDate(3, 8, 9, 5) },
      { sessionId: 'demo-sub2-insights', role: 'frontend-dev', durationMinutes: 30, linesOfCode: 210, date: isoDate(3, 8, 9, 5) },
      { sessionId: 'demo-sub3-insights', role: 'qa-engineer', durationMinutes: 20, linesOfCode: 115, date: isoDate(3, 8, 9, 6) },
      { sessionId: 'demo-sub4-insights', role: 'code-reviewer', durationMinutes: 12, linesOfCode: 20, date: isoDate(3, 8, 9, 6) },
    ],
  },
  {
    id: 'demo-y7z8-a9b0',
    title: 'Add data export with PDF report generation',
    date: isoDate(3, 10, 14, 0),
    durationMinutes: 55,
    wallClockMinutes: 68,
    turns: 35,
    linesOfCode: 450,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'cursor',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['PDF report generation', 'Monthly statement template', 'CSV export option'],
    skills: ['TypeScript', 'Next.js', 'PDF generation'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 15 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 7 },
      { tool: 'Write', count: 4 },
    ],
    filesChanged: [
      { path: 'src/lib/pdf-report.ts', additions: 165, deletions: 0 },
      { path: 'src/app/api/export/pdf/route.ts', additions: 85, deletions: 0 },
      { path: 'src/app/api/export/csv/route.ts', additions: 55, deletions: 0 },
      { path: 'src/components/ExportDialog.tsx', additions: 95, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 34,
  },
  {
    id: 'demo-c1d2-e3f4',
    title: 'Implement multi-currency support with exchange rates',
    date: isoDate(3, 12, 10, 15),
    durationMinutes: 82,
    wallClockMinutes: 100,
    turns: 55,
    linesOfCode: 710,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Multi-currency accounts', 'Exchange rate API integration', 'Conversion logic'],
    skills: ['TypeScript', 'Prisma', 'PostgreSQL'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 22 },
      { tool: 'Read', count: 14 },
      { tool: 'Bash', count: 11 },
      { tool: 'Write', count: 4 },
    ],
    filesChanged: [
      { path: 'src/lib/exchange-rates.ts', additions: 120, deletions: 0 },
      { path: 'prisma/schema.prisma', additions: 18, deletions: 4 },
      { path: 'src/lib/currency-conversion.ts', additions: 95, deletions: 0 },
      { path: 'src/components/CurrencySelector.tsx', additions: 75, deletions: 0 },
      { path: 'src/lib/exchange-rates.test.ts', additions: 140, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 51,
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-curr', role: 'backend-dev', durationMinutes: 45, linesOfCode: 320, date: isoDate(3, 12, 10, 20) },
      { sessionId: 'demo-sub2-curr', role: 'frontend-dev', durationMinutes: 30, linesOfCode: 175, date: isoDate(3, 12, 10, 20) },
      { sessionId: 'demo-sub3-curr', role: 'backend-dev', durationMinutes: 25, linesOfCode: 195, date: isoDate(3, 12, 10, 21) },
      { sessionId: 'demo-sub4-curr', role: 'qa-engineer', durationMinutes: 28, linesOfCode: 140, date: isoDate(3, 12, 10, 21) },
      { sessionId: 'demo-sub5-curr', role: 'security-engineer', durationMinutes: 15, linesOfCode: 60, date: isoDate(3, 12, 10, 50) },
      { sessionId: 'demo-sub6-curr', role: 'code-reviewer', durationMinutes: 12, linesOfCode: 35, date: isoDate(3, 12, 10, 50) },
    ],
  },
  {
    id: 'demo-g5h6-i7j8',
    title: 'Fix N+1 query in account list with transaction counts',
    date: isoDate(3, 14, 15, 0),
    durationMinutes: 12,
    wallClockMinutes: 15,
    turns: 6,
    linesOfCode: 28,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Fix N+1 query', 'Use _count in Prisma include'],
    skills: ['Prisma', 'PostgreSQL'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Read', count: 3 },
      { tool: 'Edit', count: 2 },
      { tool: 'Bash', count: 2 },
    ],
    filesChanged: [
      { path: 'src/app/api/accounts/route.ts', additions: 8, deletions: 12 },
    ],
    turnTimeline: [],
    toolCalls: 7,
  },
  {
    id: 'demo-k9l0-m1n2',
    title: 'Add two-factor authentication with TOTP',
    date: isoDate(3, 16, 9, 0),
    durationMinutes: 68,
    wallClockMinutes: 80,
    turns: 44,
    linesOfCode: 560,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['TOTP-based 2FA', 'QR code generation', 'Backup codes', 'Recovery flow'],
    skills: ['TypeScript', 'Next.js', 'Security'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 18 },
      { tool: 'Read', count: 10 },
      { tool: 'Bash', count: 9 },
      { tool: 'Write', count: 5 },
    ],
    filesChanged: [
      { path: 'src/lib/totp.ts', additions: 95, deletions: 0 },
      { path: 'src/app/settings/security/page.tsx', additions: 180, deletions: 0 },
      { path: 'src/app/api/auth/2fa/setup/route.ts', additions: 75, deletions: 0 },
      { path: 'src/app/api/auth/2fa/verify/route.ts', additions: 55, deletions: 0 },
      { path: 'src/lib/backup-codes.ts', additions: 45, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 42,
  },
  {
    id: 'demo-o3p4-q5r6',
    title: 'Refactor API routes to use middleware pattern',
    date: isoDate(3, 18, 11, 30),
    durationMinutes: 45,
    wallClockMinutes: 55,
    turns: 30,
    linesOfCode: 340,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Extract auth middleware', 'Rate limiting middleware', 'Error handling wrapper'],
    skills: ['TypeScript', 'Next.js'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 16 },
      { tool: 'Read', count: 12 },
      { tool: 'Grep', count: 5 },
    ],
    filesChanged: [
      { path: 'src/lib/middleware/auth.ts', additions: 55, deletions: 0 },
      { path: 'src/lib/middleware/rate-limit.ts', additions: 45, deletions: 0 },
      { path: 'src/lib/middleware/error-handler.ts', additions: 38, deletions: 0 },
      { path: 'src/app/api/transactions/route.ts', additions: 12, deletions: 35 },
      { path: 'src/app/api/accounts/route.ts', additions: 10, deletions: 28 },
    ],
    turnTimeline: [],
    toolCalls: 33,
  },
  {
    id: 'demo-s7t8-u9v0',
    title: 'Add mobile-responsive layout with bottom navigation',
    date: isoDate(3, 20, 14, 0),
    durationMinutes: 38,
    wallClockMinutes: 45,
    turns: 24,
    linesOfCode: 290,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'cursor',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Mobile layout', 'Bottom nav bar', 'Responsive breakpoints'],
    skills: ['React', 'Tailwind CSS', 'CSS'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 10 },
      { tool: 'Read', count: 6 },
    ],
    filesChanged: [
      { path: 'src/components/BottomNav.tsx', additions: 85, deletions: 0 },
      { path: 'src/app/layout.tsx', additions: 25, deletions: 8 },
      { path: 'src/app/globals.css', additions: 45, deletions: 5 },
    ],
    turnTimeline: [],
    toolCalls: 16,
  },
  {
    id: 'demo-w1x2-y3z4',
    title: 'Set up CI pipeline with GitHub Actions',
    date: isoDate(3, 22, 9, 0),
    durationMinutes: 28,
    wallClockMinutes: 35,
    turns: 18,
    linesOfCode: 185,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['GitHub Actions workflow', 'Lint + test + build', 'PostgreSQL service container'],
    skills: ['GitHub Actions', 'CI/CD', 'PostgreSQL'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Write', count: 3 },
      { tool: 'Edit', count: 5 },
      { tool: 'Read', count: 4 },
      { tool: 'Bash', count: 6 },
    ],
    filesChanged: [
      { path: '.github/workflows/ci.yml', additions: 95, deletions: 0 },
      { path: '.github/workflows/deploy.yml', additions: 65, deletions: 0 },
      { path: 'package.json', additions: 5, deletions: 2 },
    ],
    turnTimeline: [],
    toolCalls: 18,
  },
  {
    id: 'demo-a5b6-c7d8',
    title: 'Write API documentation with OpenAPI spec',
    date: isoDate(3, 24, 10, 0),
    durationMinutes: 42,
    wallClockMinutes: 50,
    turns: 26,
    linesOfCode: 380,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'gemini',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['OpenAPI spec', 'Swagger UI integration', 'Request/response schemas'],
    skills: ['TypeScript', 'OpenAPI'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Write', count: 4 },
      { tool: 'Edit', count: 8 },
      { tool: 'Read', count: 6 },
    ],
    filesChanged: [
      { path: 'docs/openapi.yaml', additions: 285, deletions: 0 },
      { path: 'src/app/api/docs/route.ts', additions: 45, deletions: 0 },
      { path: 'package.json', additions: 3, deletions: 1 },
    ],
    turnTimeline: [],
    toolCalls: 18,
  },
  {
    id: 'demo-e9f0-g1h2',
    title: 'Performance audit and bundle size optimization',
    date: isoDate(3, 26, 15, 0),
    durationMinutes: 35,
    wallClockMinutes: 42,
    turns: 22,
    linesOfCode: 95,
    status: 'draft',
    projectName: '-Users-alex-Dev-budgetwise',
    source: 'claude',
    cwd: '/Users/alex/Dev/budgetwise',
    rawLog: ['Bundle analysis', 'Lazy load Chart.js', 'Tree-shake unused Tailwind'],
    skills: ['Next.js', 'Performance', 'Webpack'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Bash', count: 10 },
      { tool: 'Edit', count: 6 },
      { tool: 'Read', count: 5 },
    ],
    filesChanged: [
      { path: 'next.config.ts', additions: 15, deletions: 3 },
      { path: 'src/components/SpendingChart.tsx', additions: 8, deletions: 4 },
      { path: 'tailwind.config.ts', additions: 5, deletions: 2 },
    ],
    turnTimeline: [],
    toolCalls: 21,
  },
];

// ── Shellhook sessions (12) ─────────────────────────────────

const shellhookSessions: Session[] = [
  {
    id: 'demo-sh01-aa01',
    title: 'Scaffold Rust CLI with clap and project structure',
    date: isoDate(1, 15, 10, 0),
    durationMinutes: 45,
    wallClockMinutes: 55,
    turns: 30,
    linesOfCode: 420,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['cargo init', 'clap argument parser', 'Subcommand structure: init, add, remove, list, run'],
    skills: ['Rust', 'CLI design'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Write', count: 6 },
      { tool: 'Edit', count: 10 },
      { tool: 'Bash', count: 12 },
      { tool: 'Read', count: 4 },
    ],
    filesChanged: [
      { path: 'src/main.rs', additions: 85, deletions: 0 },
      { path: 'src/cli.rs', additions: 120, deletions: 0 },
      { path: 'src/lib.rs', additions: 15, deletions: 0 },
      { path: 'Cargo.toml', additions: 22, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 32,
  },
  {
    id: 'demo-sh02-bb02',
    title: 'Implement TOML config parser for hook definitions',
    date: isoDate(1, 17, 14, 0),
    durationMinutes: 58,
    wallClockMinutes: 70,
    turns: 38,
    linesOfCode: 510,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['TOML config format design', 'Serde deserialization', 'Config validation'],
    skills: ['Rust', 'TOML parsing'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 14 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 10 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/config.rs', additions: 185, deletions: 0 },
      { path: 'src/config_test.rs', additions: 210, deletions: 0 },
      { path: 'Cargo.toml', additions: 4, deletions: 1 },
      { path: 'tests/fixtures/valid.toml', additions: 35, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 35,
  },
  {
    id: 'demo-sh03-cc03',
    title: 'Build git hook installer that symlinks to shellhook runner',
    date: isoDate(1, 20, 10, 30),
    durationMinutes: 72,
    wallClockMinutes: 88,
    turns: 48,
    linesOfCode: 580,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Git hook installation', 'Symlink strategy', 'Backup existing hooks', 'Cross-platform path handling'],
    skills: ['Rust', 'Git internals', 'Shell scripting'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 18 },
      { tool: 'Read', count: 10 },
      { tool: 'Bash', count: 14 },
      { tool: 'Grep', count: 3 },
    ],
    filesChanged: [
      { path: 'src/installer.rs', additions: 220, deletions: 0 },
      { path: 'src/runner.rs', additions: 145, deletions: 0 },
      { path: 'src/installer_test.rs', additions: 180, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 45,
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-hook', role: 'backend-dev', durationMinutes: 40, linesOfCode: 320, date: isoDate(1, 20, 10, 35) },
      { sessionId: 'demo-sub2-hook', role: 'qa-engineer', durationMinutes: 25, linesOfCode: 180, date: isoDate(1, 20, 10, 35) },
      { sessionId: 'demo-sub3-hook', role: 'backend-dev', durationMinutes: 20, linesOfCode: 145, date: isoDate(1, 20, 10, 36) },
      { sessionId: 'demo-sub4-hook', role: 'security-engineer', durationMinutes: 15, linesOfCode: 80, date: isoDate(1, 20, 11, 5) },
      { sessionId: 'demo-sub5-hook', role: 'code-reviewer', durationMinutes: 10, linesOfCode: 35, date: isoDate(1, 20, 11, 5) },
    ],
  },
  {
    id: 'demo-sh04-dd04',
    title: 'Refactor CLI argument parser to support subcommands',
    date: isoDate(1, 22, 15, 0),
    durationMinutes: 35,
    wallClockMinutes: 42,
    turns: 22,
    linesOfCode: 280,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Refactor clap to use derive API', 'Add init, add, remove, list subcommands'],
    skills: ['Rust', 'CLI design'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 12 },
      { tool: 'Read', count: 6 },
      { tool: 'Bash', count: 5 },
    ],
    filesChanged: [
      { path: 'src/cli.rs', additions: 95, deletions: 65 },
      { path: 'src/main.rs', additions: 45, deletions: 30 },
      { path: 'src/commands/mod.rs', additions: 25, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 23,
  },
  {
    id: 'demo-sh05-ee05',
    title: 'Add hook execution with timeout and error handling',
    date: isoDate(1, 25, 9, 0),
    durationMinutes: 65,
    wallClockMinutes: 78,
    turns: 42,
    linesOfCode: 490,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Hook execution engine', 'Configurable timeouts', 'Stderr/stdout capture', 'Exit code propagation'],
    skills: ['Rust', 'Shell scripting'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 16 },
      { tool: 'Read', count: 9 },
      { tool: 'Bash', count: 12 },
    ],
    filesChanged: [
      { path: 'src/executor.rs', additions: 195, deletions: 0 },
      { path: 'src/executor_test.rs', additions: 165, deletions: 0 },
      { path: 'src/runner.rs', additions: 45, deletions: 12 },
    ],
    turnTimeline: [],
    toolCalls: 37,
  },
  {
    id: 'demo-sh06-ff06',
    title: 'Implement hook ordering with dependency resolution',
    date: isoDate(1, 28, 11, 0),
    durationMinutes: 55,
    wallClockMinutes: 65,
    turns: 36,
    linesOfCode: 420,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Topological sort for hook dependencies', 'Cycle detection', 'Parallel execution for independent hooks'],
    skills: ['Rust', 'Algorithm design'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 14 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 10 },
    ],
    filesChanged: [
      { path: 'src/ordering.rs', additions: 165, deletions: 0 },
      { path: 'src/ordering_test.rs', additions: 185, deletions: 0 },
      { path: 'src/config.rs', additions: 22, deletions: 5 },
    ],
    turnTimeline: [],
    toolCalls: 32,
  },
  {
    id: 'demo-sh07-gg07',
    title: 'Add colored output and progress indicators',
    date: isoDate(2, 1, 14, 30),
    durationMinutes: 22,
    wallClockMinutes: 28,
    turns: 14,
    linesOfCode: 165,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'cursor',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Colored terminal output', 'Progress spinners for long hooks', 'Respect NO_COLOR env var'],
    skills: ['Rust', 'CLI design'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 8 },
      { tool: 'Read', count: 4 },
      { tool: 'Bash', count: 3 },
    ],
    filesChanged: [
      { path: 'src/output.rs', additions: 95, deletions: 0 },
      { path: 'src/runner.rs', additions: 35, deletions: 10 },
      { path: 'Cargo.toml', additions: 3, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 15,
  },
  {
    id: 'demo-sh08-hh08',
    title: 'Fix path resolution on Windows with UNC paths',
    date: isoDate(2, 3, 10, 0),
    durationMinutes: 28,
    wallClockMinutes: 35,
    turns: 18,
    linesOfCode: 145,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Windows UNC path handling', 'Cross-platform path normalization'],
    skills: ['Rust', 'Cross-platform'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 7 },
      { tool: 'Read', count: 5 },
      { tool: 'Bash', count: 6 },
    ],
    filesChanged: [
      { path: 'src/paths.rs', additions: 65, deletions: 8 },
      { path: 'src/paths_test.rs', additions: 72, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 18,
  },
  {
    id: 'demo-sh09-ii09',
    title: 'Add shellhook init command with interactive setup',
    date: isoDate(2, 5, 13, 0),
    durationMinutes: 40,
    wallClockMinutes: 48,
    turns: 26,
    linesOfCode: 320,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Interactive init command', 'Detect existing hooks', 'Generate starter config'],
    skills: ['Rust', 'CLI design', 'Git internals'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 12 },
      { tool: 'Read', count: 7 },
      { tool: 'Bash', count: 8 },
      { tool: 'Write', count: 2 },
    ],
    filesChanged: [
      { path: 'src/commands/init.rs', additions: 145, deletions: 0 },
      { path: 'src/commands/init_test.rs', additions: 120, deletions: 0 },
      { path: 'templates/default.toml', additions: 35, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 29,
  },
  {
    id: 'demo-sh10-jj10',
    title: 'Write integration tests with temp git repos',
    date: isoDate(2, 8, 10, 0),
    durationMinutes: 52,
    wallClockMinutes: 62,
    turns: 34,
    linesOfCode: 445,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Integration test harness', 'Temp git repo fixtures', 'Test all hook lifecycle operations'],
    skills: ['Rust', 'Testing', 'Git internals'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 16 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 14 },
      { tool: 'Write', count: 4 },
    ],
    filesChanged: [
      { path: 'tests/integration/lifecycle.rs', additions: 225, deletions: 0 },
      { path: 'tests/integration/helpers.rs', additions: 85, deletions: 0 },
      { path: 'tests/integration/mod.rs', additions: 10, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 42,
  },
  {
    id: 'demo-sh11-kk11',
    title: 'Add shell completion generation for bash/zsh/fish',
    date: isoDate(2, 10, 15, 0),
    durationMinutes: 18,
    wallClockMinutes: 22,
    turns: 10,
    linesOfCode: 85,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'claude',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['clap_complete for shell completions', 'Generate for bash, zsh, fish'],
    skills: ['Rust', 'CLI design', 'Shell scripting'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 5 },
      { tool: 'Read', count: 3 },
      { tool: 'Bash', count: 4 },
    ],
    filesChanged: [
      { path: 'src/commands/completions.rs', additions: 45, deletions: 0 },
      { path: 'src/cli.rs', additions: 12, deletions: 2 },
      { path: 'Cargo.toml', additions: 2, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 12,
  },
  {
    id: 'demo-sh12-ll12',
    title: 'Publish to crates.io with README and changelog',
    date: isoDate(2, 12, 9, 0),
    durationMinutes: 22,
    wallClockMinutes: 28,
    turns: 14,
    linesOfCode: 180,
    status: 'draft',
    projectName: '-Users-alex-Dev-shellhook',
    source: 'gemini',
    cwd: '/Users/alex/Dev/shellhook',
    rawLog: ['Cargo.toml metadata', 'README with usage examples', 'CHANGELOG.md'],
    skills: ['Rust', 'Documentation'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Write', count: 3 },
      { tool: 'Edit', count: 5 },
      { tool: 'Read', count: 3 },
      { tool: 'Bash', count: 4 },
    ],
    filesChanged: [
      { path: 'Cargo.toml', additions: 18, deletions: 3 },
      { path: 'README.md', additions: 120, deletions: 0 },
      { path: 'CHANGELOG.md', additions: 42, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 15,
  },
];

// ── Pixelboard sessions (6) ─────────────────────────────────

const pixelboardSessions: Session[] = [
  {
    id: 'demo-pb01-aa01',
    title: 'Set up Express server with WebSocket upgrade handling',
    date: isoDate(3, 15, 10, 0),
    durationMinutes: 48,
    wallClockMinutes: 58,
    turns: 32,
    linesOfCode: 380,
    status: 'draft',
    projectName: '-Users-alex-Dev-pixelboard',
    source: 'claude',
    cwd: '/Users/alex/Dev/pixelboard',
    rawLog: ['Express + ws server', 'WebSocket upgrade on /ws', 'Room-based connection management'],
    skills: ['TypeScript', 'Express', 'WebSocket'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Write', count: 5 },
      { tool: 'Edit', count: 12 },
      { tool: 'Bash', count: 8 },
      { tool: 'Read', count: 4 },
    ],
    filesChanged: [
      { path: 'src/server.ts', additions: 125, deletions: 0 },
      { path: 'src/ws/connection-manager.ts', additions: 145, deletions: 0 },
      { path: 'src/ws/protocol.ts', additions: 65, deletions: 0 },
      { path: 'package.json', additions: 28, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 29,
  },
  {
    id: 'demo-pb02-bb02',
    title: 'Build Canvas rendering layer with pressure-sensitive drawing',
    date: isoDate(3, 17, 14, 0),
    durationMinutes: 65,
    wallClockMinutes: 78,
    turns: 44,
    linesOfCode: 580,
    status: 'draft',
    projectName: '-Users-alex-Dev-pixelboard',
    source: 'claude',
    cwd: '/Users/alex/Dev/pixelboard',
    rawLog: ['Canvas 2D rendering', 'Pressure-sensitive strokes', 'Smooth curve interpolation'],
    skills: ['TypeScript', 'Canvas API'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 18 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 6 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/client/canvas-renderer.ts', additions: 245, deletions: 0 },
      { path: 'src/client/stroke-engine.ts', additions: 185, deletions: 0 },
      { path: 'src/client/input-handler.ts', additions: 95, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 35,
  },
  {
    id: 'demo-pb03-cc03',
    title: 'Implement CRDT-based state sync for concurrent edits',
    date: isoDate(3, 19, 10, 0),
    durationMinutes: 85,
    wallClockMinutes: 105,
    turns: 58,
    linesOfCode: 720,
    status: 'draft',
    projectName: '-Users-alex-Dev-pixelboard',
    source: 'claude',
    cwd: '/Users/alex/Dev/pixelboard',
    rawLog: ['CRDT for stroke ordering', 'Vector clock for causal ordering', 'Conflict resolution for overlapping strokes'],
    skills: ['TypeScript', 'CRDT', 'WebSocket'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 22 },
      { tool: 'Read', count: 12 },
      { tool: 'Bash', count: 14 },
      { tool: 'Write', count: 4 },
    ],
    filesChanged: [
      { path: 'src/sync/crdt.ts', additions: 285, deletions: 0 },
      { path: 'src/sync/vector-clock.ts', additions: 95, deletions: 0 },
      { path: 'src/sync/crdt.test.ts', additions: 240, deletions: 0 },
      { path: 'src/ws/protocol.ts', additions: 35, deletions: 8 },
    ],
    turnTimeline: [],
    toolCalls: 52,
    isOrchestrated: true,
    children: [
      { sessionId: 'demo-sub1-crdt', role: 'backend-dev', durationMinutes: 50, linesOfCode: 380, date: isoDate(3, 18, 11, 5) },
      { sessionId: 'demo-sub2-crdt', role: 'frontend-dev', durationMinutes: 40, linesOfCode: 240, date: isoDate(3, 18, 11, 5) },
      { sessionId: 'demo-sub3-crdt', role: 'backend-dev', durationMinutes: 35, linesOfCode: 290, date: isoDate(3, 18, 11, 6) },
      { sessionId: 'demo-sub4-crdt', role: 'qa-engineer', durationMinutes: 30, linesOfCode: 200, date: isoDate(3, 18, 11, 6) },
      { sessionId: 'demo-sub5-crdt', role: 'security-engineer', durationMinutes: 25, linesOfCode: 150, date: isoDate(3, 18, 11, 6) },
      { sessionId: 'demo-sub6-crdt', role: 'code-reviewer', durationMinutes: 15, linesOfCode: 60, date: isoDate(3, 18, 11, 40) },
      { sessionId: 'demo-sub7-crdt', role: 'frontend-dev', durationMinutes: 20, linesOfCode: 170, date: isoDate(3, 18, 11, 40) },
      { sessionId: 'demo-sub8-crdt', role: 'qa-engineer', durationMinutes: 18, linesOfCode: 120, date: isoDate(3, 18, 11, 41) },
      { sessionId: 'demo-sub9-crdt', role: 'security-red-teamer', durationMinutes: 12, linesOfCode: 40, date: isoDate(3, 18, 11, 41) },
      { sessionId: 'demo-sub10-crdt', role: 'backend-dev', durationMinutes: 22, linesOfCode: 180, date: isoDate(3, 18, 11, 41) },
    ],
  },
  {
    id: 'demo-pb04-dd04',
    title: 'Fix WebSocket reconnection race condition',
    date: isoDate(3, 21, 16, 0),
    durationMinutes: 25,
    wallClockMinutes: 30,
    turns: 16,
    linesOfCode: 120,
    status: 'draft',
    projectName: '-Users-alex-Dev-pixelboard',
    source: 'claude',
    cwd: '/Users/alex/Dev/pixelboard',
    rawLog: ['Race condition: reconnect while old connection still closing', 'Add connection state machine'],
    skills: ['TypeScript', 'WebSocket'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 6 },
      { tool: 'Read', count: 5 },
      { tool: 'Bash', count: 4 },
    ],
    filesChanged: [
      { path: 'src/client/ws-client.ts', additions: 55, deletions: 22 },
      { path: 'src/client/ws-client.test.ts', additions: 65, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 15,
  },
  {
    id: 'demo-pb05-ee05',
    title: 'Add Redis pub/sub for multi-server board state',
    date: isoDate(3, 23, 10, 30),
    durationMinutes: 55,
    wallClockMinutes: 65,
    turns: 36,
    linesOfCode: 380,
    status: 'draft',
    projectName: '-Users-alex-Dev-pixelboard',
    source: 'claude',
    cwd: '/Users/alex/Dev/pixelboard',
    rawLog: ['Redis pub/sub for cross-server sync', 'Board state persistence', 'Connection handoff on reconnect'],
    skills: ['TypeScript', 'Redis', 'WebSocket'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 14 },
      { tool: 'Read', count: 8 },
      { tool: 'Bash', count: 10 },
      { tool: 'Write', count: 2 },
    ],
    filesChanged: [
      { path: 'src/store/redis-adapter.ts', additions: 145, deletions: 0 },
      { path: 'src/store/board-state.ts', additions: 95, deletions: 0 },
      { path: 'src/ws/connection-manager.ts', additions: 45, deletions: 15 },
      { path: 'docker-compose.yml', additions: 18, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 34,
  },
  {
    id: 'demo-pb06-ff06',
    title: 'Build toolbar UI with tool selection and color picker',
    date: isoDate(3, 25, 14, 0),
    durationMinutes: 38,
    wallClockMinutes: 45,
    turns: 24,
    linesOfCode: 310,
    status: 'draft',
    projectName: '-Users-alex-Dev-pixelboard',
    source: 'cursor',
    cwd: '/Users/alex/Dev/pixelboard',
    rawLog: ['Drawing toolbar', 'Tool selection (pen, eraser, shapes)', 'Color picker with recent colors'],
    skills: ['TypeScript', 'Canvas API', 'CSS'],
    executionPath: [],
    toolBreakdown: [
      { tool: 'Edit', count: 10 },
      { tool: 'Read', count: 5 },
      { tool: 'Write', count: 3 },
    ],
    filesChanged: [
      { path: 'src/client/toolbar.ts', additions: 145, deletions: 0 },
      { path: 'src/client/color-picker.ts', additions: 85, deletions: 0 },
      { path: 'src/client/styles.css', additions: 65, deletions: 0 },
    ],
    turnTimeline: [],
    toolCalls: 18,
  },
];

// ── All sessions ─────────────────────────────────────────────

export const DEMO_SESSIONS: Session[] = [
  ...budgetwiseSessions,
  ...shellhookSessions,
  ...pixelboardSessions,
];

// ── Search results ───────────────────────────────────────────

export const DEMO_SEARCH_RESULTS: SearchResult[] = [
  {
    sessionId: 'demo-a1b2-c3d4',
    title: 'Set up Prisma schema with User, Account, and Transaction models',
    projectDir: '-Users-alex-Dev-budgetwise',
    projectName: 'budgetwise',
    source: 'claude',
    date: isoDate(2, 3, 9, 15),
    durationMinutes: 72,
    turns: 45,
    linesOfCode: 680,
    skills: ['TypeScript', 'Prisma', 'PostgreSQL'],
    snippet: 'Created User model with email/password, Account with balance tracking, and <mark>Transaction</mark> with discriminated union for type safety',
    score: 0.95,
  },
  {
    sessionId: 'demo-i9j0-k1l2',
    title: 'Implement recurring transaction detection algorithm',
    projectDir: '-Users-alex-Dev-budgetwise',
    projectName: 'budgetwise',
    source: 'claude',
    date: isoDate(2, 7, 10, 30),
    durationMinutes: 88,
    turns: 62,
    linesOfCode: 890,
    skills: ['TypeScript', 'PostgreSQL', 'Algorithm design'],
    snippet: 'Grouped transactions by normalized merchant + amount, detected <mark>recurring</mark> patterns with tolerance windows',
    score: 0.91,
  },
  {
    sessionId: 'demo-sh03-cc03',
    title: 'Build git hook installer that symlinks to shellhook runner',
    projectDir: '-Users-alex-Dev-shellhook',
    projectName: 'shellhook',
    source: 'claude',
    date: isoDate(1, 20, 10, 30),
    durationMinutes: 72,
    turns: 48,
    linesOfCode: 580,
    skills: ['Rust', 'Git internals', 'Shell scripting'],
    snippet: 'Symlink-based <mark>hook installation</mark> with backup of existing hooks and cross-platform path handling',
    score: 0.88,
  },
  {
    sessionId: 'demo-pb03-cc03',
    title: 'Implement CRDT-based state sync for concurrent edits',
    projectDir: '-Users-alex-Dev-pixelboard',
    projectName: 'pixelboard',
    source: 'claude',
    date: isoDate(3, 19, 10, 0),
    durationMinutes: 85,
    turns: 58,
    linesOfCode: 720,
    skills: ['TypeScript', 'CRDT', 'WebSocket'],
    snippet: 'Vector clock for causal ordering, <mark>CRDT</mark> conflict resolution for overlapping strokes from concurrent users',
    score: 0.87,
  },
  {
    sessionId: 'demo-c9d0-e1f2',
    title: 'Build CSV import for bank statements',
    projectDir: '-Users-alex-Dev-budgetwise',
    projectName: 'budgetwise',
    source: 'claude',
    date: isoDate(2, 17, 9, 45),
    durationMinutes: 78,
    turns: 52,
    linesOfCode: 640,
    skills: ['TypeScript', 'React', 'Next.js'],
    snippet: 'Column mapping UI for <mark>CSV import</mark>, duplicate detection on transaction hash',
    score: 0.84,
  },
  {
    sessionId: 'demo-pb04-dd04',
    title: 'Fix WebSocket reconnection race condition',
    projectDir: '-Users-alex-Dev-pixelboard',
    projectName: 'pixelboard',
    source: 'claude',
    date: isoDate(3, 21, 16, 0),
    durationMinutes: 25,
    turns: 16,
    linesOfCode: 120,
    skills: ['TypeScript', 'WebSocket'],
    snippet: 'Race condition when <mark>reconnecting</mark> while old connection still in CLOSING state — added state machine',
    score: 0.82,
  },
  {
    sessionId: 'demo-m3n4-o5p6',
    title: 'Add Stripe integration for premium features',
    projectDir: '-Users-alex-Dev-budgetwise',
    projectName: 'budgetwise',
    source: 'claude',
    date: isoDate(2, 10, 9, 0),
    durationMinutes: 55,
    turns: 35,
    linesOfCode: 420,
    skills: ['TypeScript', 'Stripe API', 'Next.js'],
    snippet: 'Checkout session creation, <mark>webhook</mark> handler for payment events, premium feature gating middleware',
    score: 0.79,
  },
  {
    sessionId: 'demo-sh06-ff06',
    title: 'Implement hook ordering with dependency resolution',
    projectDir: '-Users-alex-Dev-shellhook',
    projectName: 'shellhook',
    source: 'claude',
    date: isoDate(1, 28, 11, 0),
    durationMinutes: 55,
    turns: 36,
    linesOfCode: 420,
    skills: ['Rust', 'Algorithm design'],
    snippet: 'Topological sort for <mark>hook dependencies</mark>, cycle detection, parallel execution for independent hooks',
    score: 0.76,
  },
  {
    sessionId: 'demo-k9l0-m1n2',
    title: 'Add two-factor authentication with TOTP',
    projectDir: '-Users-alex-Dev-budgetwise',
    projectName: 'budgetwise',
    source: 'claude',
    date: isoDate(3, 16, 9, 0),
    durationMinutes: 68,
    turns: 44,
    linesOfCode: 560,
    skills: ['TypeScript', 'Next.js', 'Security'],
    snippet: 'TOTP-based <mark>2FA</mark> with QR code generation, backup codes, and recovery flow',
    score: 0.73,
  },
  {
    sessionId: 'demo-sh02-bb02',
    title: 'Implement TOML config parser for hook definitions',
    projectDir: '-Users-alex-Dev-shellhook',
    projectName: 'shellhook',
    source: 'claude',
    date: isoDate(1, 17, 14, 0),
    durationMinutes: 58,
    turns: 38,
    linesOfCode: 510,
    skills: ['Rust', 'TOML parsing'],
    snippet: 'Serde deserialization of <mark>TOML config</mark> with validation, typed hook definitions, test fixtures',
    score: 0.70,
  },
];

// ── Transcript ───────────────────────────────────────────────

export const DEMO_TRANSCRIPT: TranscriptResponse = {
  messages: [
    {
      id: 'msg-001',
      timestamp: isoDate(2, 3, 9, 15),
      role: 'user',
      blocks: [
        {
          type: 'text',
          text: 'Set up a Prisma schema for a personal finance app. I need User, Account, and Transaction models. Transactions should support different types — income, expense, and transfer. Use a discriminated union pattern, not single-table inheritance.',
        },
      ],
    },
    {
      id: 'msg-002',
      timestamp: isoDate(2, 3, 9, 16),
      role: 'assistant',
      model: 'claude-opus-4-0-20250514',
      blocks: [
        {
          type: 'thinking',
          text: 'The user wants a Prisma schema with three models. They specifically want a discriminated union for transaction types, which means separate models for each type with a shared interface. Let me check if there is an existing schema file first.',
        },
        {
          type: 'tool_call',
          toolCallId: 'tc-001',
          toolName: 'Read',
          input: 'prisma/schema.prisma',
          output: 'File not found: prisma/schema.prisma',
        },
        {
          type: 'tool_call',
          toolCallId: 'tc-002',
          toolName: 'Bash',
          input: 'npx prisma init --datasource-provider postgresql',
          output: '✔ Your Prisma schema was created at prisma/schema.prisma\n✔ .env file created',
        },
        {
          type: 'text',
          text: 'Initialized Prisma with PostgreSQL. Now I will write the schema with the three models. For the discriminated union, I will use an enum `TransactionType` with a `type` field on the Transaction model, plus optional relation fields that are only populated for specific types.',
        },
      ],
    },
    {
      id: 'msg-003',
      timestamp: isoDate(2, 3, 9, 20),
      role: 'assistant',
      model: 'claude-opus-4-0-20250514',
      blocks: [
        {
          type: 'tool_call',
          toolCallId: 'tc-003',
          toolName: 'Edit',
          input: 'prisma/schema.prisma',
          output: 'File updated: prisma/schema.prisma (+142 lines)',
        },
        {
          type: 'text',
          text: 'Here is the schema. Key design decisions:\n\n1. `TransactionType` enum with INCOME, EXPENSE, and TRANSFER variants\n2. Transfer-specific fields (`transferToAccountId`, `transferToAccount`) are nullable — only populated when type is TRANSFER\n3. `Account.balance` is a computed field derived from transactions, not stored directly\n4. Composite index on `(accountId, createdAt)` for the transaction list query\n5. Unique constraint on `User.email`\n\nThe balance reconciliation will be a separate concern — for now the schema supports it by making all transactions immutable (no update, only create and soft-delete via a `deletedAt` field).',
        },
      ],
    },
    {
      id: 'msg-004',
      timestamp: isoDate(2, 3, 9, 25),
      role: 'user',
      blocks: [
        {
          type: 'text',
          text: 'Looks good but drop the soft delete. Use hard deletes with an audit log table instead. Also add a `recurringSchedule` field for transactions that repeat — nullable, only for recurring ones.',
        },
      ],
    },
    {
      id: 'msg-005',
      timestamp: isoDate(2, 3, 9, 27),
      role: 'assistant',
      model: 'claude-opus-4-0-20250514',
      blocks: [
        {
          type: 'text',
          text: 'Good call on the audit log — soft deletes would complicate every query. I will add a `TransactionAuditLog` table and a `recurringSchedule` JSON field.',
        },
        {
          type: 'tool_call',
          toolCallId: 'tc-004',
          toolName: 'Edit',
          input: 'prisma/schema.prisma',
          output: 'File updated: prisma/schema.prisma (+28 -12 lines)',
        },
      ],
    },
    {
      id: 'msg-006',
      timestamp: isoDate(2, 3, 9, 35),
      role: 'user',
      blocks: [
        {
          type: 'text',
          text: 'Run the migration and create a seed script with some test data.',
        },
      ],
    },
    {
      id: 'msg-007',
      timestamp: isoDate(2, 3, 9, 37),
      role: 'assistant',
      model: 'claude-opus-4-0-20250514',
      blocks: [
        {
          type: 'tool_call',
          toolCallId: 'tc-005',
          toolName: 'Bash',
          input: 'npx prisma migrate dev --name init',
          output: 'Applying migration `20260203091500_init`\n\nThe following migration has been created and applied:\nmigrations/20260203091500_init/migration.sql\n\nYour database is now in sync with your schema.',
        },
        {
          type: 'tool_call',
          toolCallId: 'tc-006',
          toolName: 'Edit',
          input: 'prisma/seed.ts',
          output: 'File created: prisma/seed.ts (+89 lines)',
        },
        {
          type: 'tool_call',
          toolCallId: 'tc-007',
          toolName: 'Bash',
          input: 'npx tsx prisma/seed.ts',
          output: 'Seeded: 2 users, 4 accounts, 47 transactions',
        },
        {
          type: 'text',
          text: 'Migration applied and seed data created. The seed script creates two users, each with checking and savings accounts, and a mix of income, expense, and transfer transactions spanning the last 3 months.',
        },
      ],
    },
    {
      id: 'msg-008',
      timestamp: isoDate(2, 3, 9, 45),
      role: 'user',
      blocks: [
        {
          type: 'text',
          text: 'Now set up the Prisma client singleton so we can use it across the app.',
        },
      ],
    },
    {
      id: 'msg-009',
      timestamp: isoDate(2, 3, 9, 47),
      role: 'assistant',
      model: 'claude-opus-4-0-20250514',
      blocks: [
        {
          type: 'tool_call',
          toolCallId: 'tc-008',
          toolName: 'Grep',
          input: 'PrismaClient',
          output: 'prisma/seed.ts:1: import { PrismaClient } from \'@prisma/client\'',
        },
        {
          type: 'tool_call',
          toolCallId: 'tc-009',
          toolName: 'Edit',
          input: 'src/lib/db.ts',
          output: 'File created: src/lib/db.ts (+34 lines)',
        },
        {
          type: 'text',
          text: 'Created the client singleton at `src/lib/db.ts`. It reuses the client in development (attached to `globalThis` to survive hot reloads) and creates a fresh instance in production. The client is typed and exported as `prisma`.',
        },
      ],
    },
  ],
  meta: {
    totalMessages: 9,
    totalTokens: { input: 12480, output: 8920 },
    models: ['claude-opus-4-0-20250514'],
    duration: { activeMinutes: 72, wallClockMinutes: 87 },
  },
};

// ── Dashboard ────────────────────────────────────────────────

function computeProjectStats(
  sessions: Session[],
  proj: typeof DEMO_PROJECTS[keyof typeof DEMO_PROJECTS],
) {
  const projSessions = sessions.filter((s) => s.projectName === proj.dirName);
  const totalLoc = projSessions.reduce((sum, s) => sum + s.linesOfCode, 0);
  const totalDuration = projSessions.reduce((sum, s) => sum + s.durationMinutes, 0);
  const totalTurns = projSessions.reduce((sum, s) => sum + s.turns, 0);
  const latestDate = projSessions
    .map((s) => s.date)
    .sort()
    .pop() ?? '';
  const enhancedCount = projSessions.filter((s) => s.status === 'enhanced').length;

  return {
    projectDir: proj.dirName,
    projectName: proj.name,
    sessionCount: projSessions.length,
    totalLoc,
    totalDuration,
    totalTurns,
    skills: [...proj.skills],
    latestDate,
    enhancedAt: enhancedCount > 0 ? isoDate(3, 28, 12, 0) : null,
  };
}

export const DEMO_DASHBOARD = {
  stats: {
    sessionCount: DEMO_SESSIONS.length,
    projectCount: 3,
    sourceCount: 3,
    enhancedCount: 3,
  },
  projects: [
    computeProjectStats(DEMO_SESSIONS, DEMO_PROJECTS.budgetwise),
    computeProjectStats(DEMO_SESSIONS, DEMO_PROJECTS.shellhook),
    computeProjectStats(DEMO_SESSIONS, DEMO_PROJECTS.pixelboard),
  ],
  sync: { status: 'done' as const, phase: 'done' as const, current: DEMO_SESSIONS.length, total: DEMO_SESSIONS.length },
  isEmpty: false,
  onboardingComplete: true,
};

// ── Enhance result ───────────────────────────────────────────

export const DEMO_ENHANCE_RESULT = {
  narrative: `Started with a basic Prisma schema but realized halfway through that I needed polymorphic transaction types. The AI kept suggesting single-table inheritance but I pushed back — went with a discriminated union pattern instead. Nullable fields for transfer-specific data, hard deletes with an audit log.

The recurring transaction detection was the hardest part. Had to figure out the right tolerance windows — monthly transactions drift by a few days, weekly ones are more precise. Settled on three consecutive interval matches before marking something as recurring. The partial index on merchant_normalized brought the detection query from 2 seconds to 120ms on 10k transactions.

Plaid integration went smoother than expected. The token exchange flow is straightforward, but the webhook handling needed careful idempotency — Plaid sends duplicate webhooks, so I used a processed-events table keyed on webhook ID. The CSV import was the fallback path for banks Plaid doesn't support.

Biggest lesson: I spent too long on the dashboard charts before the core transaction logic was solid. Should have built the spending insights and budget alerts first — those drove most of the schema changes that rippled through the whole codebase.`,
  arc: [
    { phase: 1, title: 'Foundation', description: 'Schema design, Prisma setup, and core transaction CRUD. Established the discriminated union pattern for transaction types.' },
    { phase: 2, title: 'Data pipeline', description: 'CSV import, Plaid integration, and recurring detection. Focused on getting real data flowing through the system.' },
    { phase: 3, title: 'Intelligence layer', description: 'Budget categories, spending insights, and anomaly detection. The analysis features that make the data useful.' },
    { phase: 4, title: 'Polish', description: 'Multi-currency, 2FA, performance optimization, dark mode. Hardening for real-world use.' },
  ],
  skills: ['TypeScript', 'React', 'Next.js', 'Prisma', 'PostgreSQL', 'Tailwind CSS', 'Stripe API', 'Plaid API', 'Chart.js', 'Playwright'],
  timeline: [
    {
      period: 'Feb 3 – Feb 14',
      label: 'Foundation',
      sessions: [
        { sessionId: 'demo-a1b2-c3d4', title: 'Set up Prisma schema with User, Account, and Transaction models', featured: true, tag: 'schema' },
        { sessionId: 'demo-e5f6-g7h8', title: 'Build transaction list page with infinite scroll', featured: true, tag: 'frontend' },
        { sessionId: 'demo-i9j0-k1l2', title: 'Implement recurring transaction detection algorithm', featured: true, tag: 'algorithm' },
        { sessionId: 'demo-m3n4-o5p6', title: 'Add Stripe integration for premium features', featured: false },
        { sessionId: 'demo-q7r8-s9t0', title: 'Design dashboard layout with spending charts', featured: false },
        { sessionId: 'demo-u1v2-w3x4', title: 'Fix currency formatting edge cases in locale-aware display', featured: false },
        { sessionId: 'demo-y5z6-a7b8', title: 'Add account balance reconciliation checks', featured: false },
      ],
    },
    {
      period: 'Feb 17 – Feb 26',
      label: 'Data pipeline',
      sessions: [
        { sessionId: 'demo-c9d0-e1f2', title: 'Build CSV import for bank statements', featured: true, tag: 'import' },
        { sessionId: 'demo-g3h4-i5j6', title: 'Implement budget categories with monthly limits', featured: true, tag: 'budgets' },
        { sessionId: 'demo-k7l8-m9n0', title: 'Add email notifications for budget overspend', featured: false },
        { sessionId: 'demo-o1p2-q3r4', title: 'Write E2E tests for transaction CRUD flow', featured: false },
        { sessionId: 'demo-s5t6-u7v8', title: 'Optimize transaction queries with composite indexes', featured: false },
        { sessionId: 'demo-w9x0-y1z2', title: 'Add dark mode with system preference detection', featured: false },
        { sessionId: 'demo-a3b4-c5d6', title: 'Build account settings page with profile editing', featured: false },
      ],
    },
    {
      period: 'Mar 1 – Mar 14',
      label: 'Intelligence + integrations',
      sessions: [
        { sessionId: 'demo-e7f8-g9h0', title: 'Implement transaction search with full-text index', featured: false },
        { sessionId: 'demo-i1j2-k3l4', title: 'Add plaid integration for bank account linking', featured: true, tag: 'integration' },
        { sessionId: 'demo-m5n6-o7p8', title: 'Fix timezone bug in monthly spending aggregation', featured: false },
        { sessionId: 'demo-q9r0-s1t2', title: 'Add transaction tagging and custom categories', featured: false },
        { sessionId: 'demo-u3v4-w5x6', title: 'Build spending insights with trend analysis', featured: true, tag: 'insights' },
        { sessionId: 'demo-y7z8-a9b0', title: 'Add data export with PDF report generation', featured: false },
        { sessionId: 'demo-c1d2-e3f4', title: 'Implement multi-currency support with exchange rates', featured: true, tag: 'currency' },
        { sessionId: 'demo-g5h6-i7j8', title: 'Fix N+1 query in account list with transaction counts', featured: false },
      ],
    },
    {
      period: 'Mar 16 – Mar 26',
      label: 'Hardening',
      sessions: [
        { sessionId: 'demo-k9l0-m1n2', title: 'Add two-factor authentication with TOTP', featured: true, tag: 'security' },
        { sessionId: 'demo-o3p4-q5r6', title: 'Refactor API routes to use middleware pattern', featured: false },
        { sessionId: 'demo-s7t8-u9v0', title: 'Add mobile-responsive layout with bottom navigation', featured: false },
        { sessionId: 'demo-w1x2-y3z4', title: 'Set up CI pipeline with GitHub Actions', featured: false },
        { sessionId: 'demo-a5b6-c7d8', title: 'Write API documentation with OpenAPI spec', featured: false },
        { sessionId: 'demo-e9f0-g1h2', title: 'Performance audit and bundle size optimization', featured: false },
      ],
    },
  ],
  questions: [
    { id: 'q-001', category: 'architecture' as const, question: 'Why a discriminated union over Prisma\'s built-in polymorphic relations?', context: 'The schema uses nullable transfer-specific fields with a type enum rather than separate tables per transaction type.' },
    { id: 'q-002', category: 'pattern' as const, question: 'How does the recurring detection handle irregular intervals like "every other Friday"?', context: 'The algorithm uses tolerance windows for matching, but biweekly patterns on specific weekdays may need special handling.' },
    { id: 'q-003', category: 'evolution' as const, question: 'What drove the decision to add Plaid after building CSV import?', context: 'CSV import was built first (Feb 17), Plaid integration came later (Mar 3). Was CSV a deliberate fallback or did Plaid scope grow?' },
    { id: 'q-004', category: 'architecture' as const, question: 'How do you handle the balance consistency problem between computed and cached values?', context: 'Account balances are derived from transactions, but caching them introduces potential drift.' },
    { id: 'q-005', category: 'pattern' as const, question: 'What is the retry strategy for failed Plaid webhook processing?', context: 'The processed-events table handles deduplication, but what happens when webhook processing fails midway?' },
  ],
};

// ── Source audit ──────────────────────────────────────────────

export const DEMO_SOURCE_AUDIT: SourceAuditResult = {
  sources: [
    {
      name: 'Claude Code',
      path: '~/.claude/projects',
      dateRange: 'Jan 15 \u2013 Mar 28, 2026',
      liveCount: 38,
      archivedCount: 12,
      health: 'healthy',
    },
    {
      name: 'Cursor',
      path: '~/.cursor/sessions',
      dateRange: 'Feb 1 \u2013 Mar 20, 2026',
      liveCount: 8,
      archivedCount: 0,
      health: 'healthy',
    },
  ],
};
